name: Test and Conditionally Publish

on:
  push:

jobs:
  # [original source of job "check-if-to-skip"](https://github.com/srz-zumix/ci-skip/blob/master/.github/workflows/main.yml#L15)
  check-if-to-skip:
    runs-on: ubuntu-latest
    # skip commits with [ci skip] or [skip ci], except on an action triggered by push of a version tag
    # TODO: remove or update git tag description
    if: "!( contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]') )"
    steps:
      - name: Check [ci skip] or [skip ci]
        run: exit 0

  e2etest:
    needs: check-if-to-skip
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12, 13, 14, 15, 16]
        os: [Ubuntu 18.04, Ubuntu 20.04]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.0.2
          run_install: true

      - name: Test
        run: |
          pnpm ts src/index.ts
